ros2-rust/ros2_rust

rclrs/src/node/mod.rs
rclrs/src/node/subscription.rs
rclrs_examples/src/rclrs_subscriber.rs

Adds the ability to subscribe with a `FnMut` closure.
Updated the example subscriber to use it.

Added closure subscribe

---

rclrs/Cargo.toml
rclrs/src/context.rs
rclrs/src/error.rs
rclrs/src/lib.rs
rclrs/src/node/mod.rs
rclrs/src/node/publisher.rs
rclrs/src/node/subscription.rs
rclrs_common/Cargo.toml
rclrs_common/src/lib.rs
rclrs_examples/Cargo.toml
rclrs_examples/src/rclrs_publisher.rs
rclrs_examples/src/rclrs_subscriber.rs

This pull request addresses issue #45 
While the conversion is taking place, if anyone can see any improvements to the error-handling system of `ros2_rust`, please let me know!

Conversion to `thiserror`

---

.github/workflows/rust.yml

Use actions below.
https://github.com/ros-tooling/action-ros-ci
https://github.com/actions-rs/toolchain

ci: refactor workflow

---

.github/workflows/rust.yml
rclrs_msg_utilities/src/lib.rs

This check is placed before build & test because it is cheap.

Check code formatting in CI

---

README.md

Added a cd command to the build instructions to make things more clear

#85 Improve Readme Build Instructions

---

rclrs/src/qos.rs

Improve the QoS module
* Add documentation
* Make depth a u32
* Put depth into enum variants
* Derive useful traits

Improve the QoS module

---

rclrs/src/context.rs
rclrs/src/node/mod.rs
rclrs_examples/Cargo.toml
rclrs_examples/src/message_demo.rs
rclrs_examples/src/minimal_publisher.rs
rclrs_examples/src/minimal_subscriber.rs

* Delete Handle wrapper
* Add SAFETY comments
* Rename default() to new() and accept Strings for usability
* Fix a few issues, such as return values not being checked

Refactor context.rs

---

rclrs_examples/src/minimal_publisher.rs
rclrs_examples/src/minimal_subscriber.rs

Undo accidental changes to minimal publisher and subscriber

---

rclrs/src/qos.rs

This allows customizing deadline, lifespan and liveliness instead of implicitly setting them to the default value.

Add missing QoS policies

---

.github/workflows/rust.yml

- update rolling to ubuntu jammy in CI
- add humble to CI
Closes #168

168 add humble hawksbill to ci

---

.github/workflows/rust.yml

Signed-off-by: Evan Flynn <evan.flynn@apex.ai>

Bump setup-ros action in CI to support Ubuntu Jammy

---

examples/message_demo/Cargo.toml
examples/message_demo/src/message_demo.rs

This function converts a message to JSON and back.

Add function to demonstrate serde integration

---

README.md
examples/minimal_pub_sub/Cargo.toml
examples/minimal_pub_sub/launch/minimal_pub_sub.launch.xml

I added minimal_pub_sub.launch.xml into example package.

feat: add example launch

---

.github/workflows/rust.yml

A simple copy-paste of the clippy step.

Add a cargo test step to CI

---

.github/workflows/rust.yml
rclrs/Cargo.toml
rclrs/package.xml
rclrs/src/context.rs
rclrs/src/lib.rs
rclrs/src/node.rs
rclrs/src/node/publisher.rs
rclrs/src/node/subscription.rs
rclrs/src/rcl_bindings.rs
rosidl_runtime_rs/src/sequence.rs

Add unit testing

---

rclrs/src/node.rs
rclrs/src/node/graph.rs
rclrs/src/rcl_wrapper.h

This PR adds support for the functionality implemented in rcl/graph.h,
as requested by #123

Add Graph Support

---

docs/building.md

I guess this was just missed in #163

change rclrs_examples to examples_rclrs_minimal_pub_sub in building.md

---

rclrs/CHANGELOG.rst

I'm following the format of other packages. Not every small PR or features is mentioned, since this is intended for humans.

Add a changelog for the rclrs package

---

rclrs/README.md
rosidl_runtime_rs/README.md

These files will be shown by crates.io.

Add README files for rclrs and rosidl_runtime_rs

---

examples/message_demo/Cargo.toml
examples/message_demo/package.xml
examples/minimal_client_service/Cargo.toml
examples/minimal_client_service/package.xml
examples/minimal_pub_sub/Cargo.toml
examples/minimal_pub_sub/package.xml
rclrs/Cargo.toml
rclrs/package.xml
rclrs_example_msgs/package.xml
rclrs_tests/Cargo.toml
rclrs_tests/package.xml
rosidl_generator_rs/package.xml
rosidl_generator_rs/resource/Cargo.toml.em
rosidl_runtime_rs/Cargo.toml
rosidl_runtime_rs/package.xml

Reverts ros2-rust/ros2_rust#343

Revert "Version 0.4.0"

---

examples/message_demo/Cargo.toml
examples/message_demo/package.xml
examples/minimal_client_service/Cargo.toml
examples/minimal_client_service/package.xml
examples/minimal_pub_sub/Cargo.toml
examples/minimal_pub_sub/package.xml
rclrs/Cargo.toml
rclrs/package.xml
rclrs_example_msgs/package.xml
rclrs_tests/Cargo.toml
rclrs_tests/package.xml
rosidl_generator_rs/package.xml
rosidl_generator_rs/resource/Cargo.toml.em
rosidl_runtime_rs/Cargo.toml
rosidl_runtime_rs/package.xml

Submitting again after fixing the `rosgraph_msgs` errors.

Version 0.4.0

---

examples/message_demo/Cargo.toml
examples/message_demo/package.xml
examples/minimal_client_service/Cargo.toml
examples/minimal_client_service/package.xml
examples/minimal_pub_sub/Cargo.toml
examples/minimal_pub_sub/package.xml
rclrs/Cargo.toml
rclrs/package.xml
rclrs_example_msgs/package.xml
rclrs_tests/Cargo.toml
rclrs_tests/package.xml
rosidl_generator_rs/package.xml
rosidl_runtime_rs/Cargo.toml
rosidl_runtime_rs/package.xml

This PR updates versions in `package.xml` and `Cargo.toml` files to 0.4.1. No major changes just a minor release so that we can push documentation to docs.rs

Version 0.4.1
