rclrs_examples/CMakeLists.txt
Addressing [https://github.com/esteve/ros2_rust/pull/3#issuecomment-468972443](https://github.com/esteve/ros2_rust/pull/3#issuecomment-468972443).
rclrs_examples crate source files are now copied at build time with CMake.
=> copy crate at build time

README.md, ros2_rust.repos
@lelongg I just realized after merging that the build instructions were slightly different than for ROS2 master, this makes it keep them in the same style.
=> Fix instructions

README.md
- corrected link to ros2_rust.repos
- added suggestion about how to install vcstools (it is not installed by default with ROS2)
=> More fixes for instructions

rosidl_generator_rs/resource/msg.rs.em, rosidl_generator_rs/rosidl_generator_rs/__init__.py
Fixes a bug in array type generation. Also append an underscore to field names that are rust keywords.
https://github.com/ros2-rust/ros2_rust/issues/26
=> Fix array type generation and field names that are keywords

README.md
colcon build fails as cmake cannot find "test_interface_files", so I added it to the Readme
=> Add test_interface-files dependency to Readme

rclrs/src/error.rs, rclrs/src/lib.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs, rclrs_common/src/lib.rs
Closes #47 
Also includes a rework of the error system around the `spin` functionality, to accept the new ways that the `WaitSet` can fail.
=> Implement WaitSet

Dockerfile
Docker ARG REPOS_FILE was not redeclared in the "cacher" build stage,
and so was not inheriting the default value specified at the top of the
file. This redeclares the arg in the "cacher" build stage, so that the
default value may be used.
On the specified version of Rust in the Dockerfile (1.47.0), a build error was encountered in rclrs_examples
```
error[E0658]: use of unstable library feature 'renamed_spin_loop'
--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.9.2/src/relax.rs:26:9
|
26 |         core::hint::spin_loop();
|         ^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information
Compiling bitvec v0.19.5
error: aborting due to previous error
```
As seen at the given link, updating Rust resolves the …
=> Fix missing Dockerfile ARG, Update Rust to 1.49.0

Dockerfile
Fixes #69 and building rclrs with rclrs_examples.
Currently, in master instructions to build and run things from Dockerfile will not work.
=> Update rust to 1.57.0 in Dockerfile

rclrs/build.rs
These tests have undefined behavior, which makes `cargo tests` produce lots of warnings. For example:
```
warning: dereferencing a null pointer
--> /home/nikolai.morin/ros2_rust/rclrs/target/debug/build/rclrs-ed1bf17021230abe/out/rcl_bindings_generated.rs:6261:19
|
6261 |         unsafe { &(*(::core::ptr::null::<rcl_wait_set_t>())).size_of_events as *const _ as usize },
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
```
=> Disable layout tests generated by bindgen

rclrs/src/lib.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs, rclrs_examples/src/minimal_publisher.rs, rclrs_examples/src/minimal_subscriber.rs
Only call `rcl_take` on ready subscription. Only trigger callbacks if subscriptions have consumed any data
Fixes #96
=> Fix spin taking messages from non-ready subscriptions

rclrs/src/lib.rs, rclrs/src/node/mod.rs, rclrs/src/wait.rs
By doing the upgrade outside of the wait set, this struct can be entirely omitted.
=> Remove unnecessary WaitSetErrorResponse

rclrs/src/node/mod.rs, rclrs/src/node/subscription.rs, rclrs_examples/src/message_demo.rs, rclrs_examples/src/minimal_subscriber.rs, rosidl_runtime_rs/Cargo.toml
This enables efficiency and ergonomics improvements: for instance, think of a node that takes incoming messages and mutates them, then re-publishes them. Or alternatively, a node could move (part of) the message into a new message to be published. When the received message is owned, this can be done with fewer copies. There is no drawback to this, since the message is already not used anymore after the callback. 
Also remove unused dependency from rosidl_runtime_rs
=> Give subscription callback the owned message

rclrs/src/wait.rs
Fix #104 
`rcl_wait` requires negative value if procedure wants to
block thread indefinitely until some messages are passed.
However, in current implementation, `timeout_ns` is set to zero,
even if `timeout` param is `None`, and this results in
making `rcl_wait` non-blocking function ( returns immediately ).
To make it correctly, I fixed to set `timeout_ns` to `-1` if `timeout` param is `None`.
=> Fix timeout_ns set value when None is passed to timeout param

rclrs/src/wait.rs
Fix #106
`minimal_subscriber` in `rclrs_examples` does not display anything.
This is because `ready_entities` in `WaitSet::wait()` collect
null `wait_set_entry` (i.e. not ready entries).
In actual, `ready_entries` should return array of "not" null `wait_set_entry`.
This fix makes so.
=> Fix to collect ready subscription entities

rclrs/Cargo.toml, rclrs/package.xml, rclrs_example_msgs/package.xml, rclrs_examples/Cargo.toml, rclrs_examples/package.xml, rosidl_generator_rs/package.xml, rosidl_generator_rs/resource/Cargo.toml.in, rosidl_runtime_rs/Cargo.toml, rosidl_runtime_rs/package.xml
The reason for the "bump" is to have a consistent version numbering across packages, not because it's needed for a release.
=> Bump every package to version 0.2

rclrs/src/node/mod.rs, rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs
This is a small simplification that makes it (imo) easier to see what's going on, besides making the code a little smaller.
=> Remove NodeHandle struct

rclrs/Cargo.toml, rclrs/build.rs, rclrs/src/context.rs, rclrs/src/error.rs, rclrs/src/lib.rs, rclrs/src/node/mod.rs, rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs, rosidl_runtime_rs/src/string.rs
This PR removes support for `no_std`, by removing the dependency for the `spin` crate and the corresponding `cfg()` blocks.
I recall @nnmm saying that `no_std` is broken (https://github.com/ros2-rust/ros2_rust/pull/88#discussion_r835641156) and I thought we might as well just remove support for it and revisit this in the future if we want to.
=> Removed support for no_std

ros2_rust_foxy.repos, ros2_rust_galactic.repos, ros2_rust_rolling.repos
It is currently not possible to simply run `colcon build`: The `test_msgs` contained in `rcl_interfaces` have a dependency on `test_interface_files`, so the build fails.
=> Add test_interface_files to the repos files

rclrs/build.rs, rclrs/src/lib.rs
This was only needed in Rust 2015.
=> Remove unnecessary "extern crate" declarations

.github/workflows/rust.yml
=> Added rustdoc check step to CI

rclrs/Cargo.toml, rosidl_runtime_rs/Cargo.toml
I got the idea from this reddit post: https://www.reddit.com/r/rust/comments/u5cjmu/dependency_justification_section_may_need_more/
=> Add comments explaining each dependency

rosidl_generator_rs/cmake/rosidl_generator_rs_generate_interfaces.cmake, rosidl_generator_rs/resource/Cargo.toml.in, rosidl_generator_rs/resource/msg.rs.em, rosidl_runtime_rs/Cargo.toml, rosidl_runtime_rs/src/sequence.rs, rosidl_runtime_rs/src/sequence/serde.rs, rosidl_runtime_rs/src/string.rs, rosidl_runtime_rs/src/string/serde.rs
The current implementation is not the most efficient one possible, except for sequence serialization: It uses `std::string::String` and `Vec` as intermediate formats instead of directly deserializing/serializing to the `rosidl_runtime_rs` datatype.
Closes #115
=> Add serde support to messages

rclrs/src/context.rs, rclrs/src/node/mod.rs
- Add Node::name, Node::namespace, Node::fully_qualified_name getters
- Add Context::create_node_with_namespace function
- Swap order of namespace and name argument in Node::new_with_namespace, so that it's less confusing
=> Add new node name-related functions

rclrs/build.rs, rclrs/src/context.rs, rclrs/src/lib.rs, rclrs/src/node/mod.rs, rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs
The references automatically coerce to raw pointers.
This also improves the signal-to-noise ratio on the `as` keyword, which is often an
antipattern (e.g. for many numeric casts).
=> Remove unnecessary casts to raw pointers

rclrs/src/node/mod.rs
Close #145 
This PR add helper method getting ROS domain ID via rcl_get_node_domain_id().
There is TODO in doc, but this should be done after support for passing node option, I think.
=> Add get_domain_id method in Node struct

rosidl_generator_rs/cmake/rosidl_generator_rs_generate_interfaces.cmake, rosidl_generator_rs/resource/build.rs.em, rosidl_generator_rs/rosidl_generator_rs/__init__.py
I think the relative path will be always correct, but even if not, this is only an _additional_ search dir.
The impact is that you can build packages depending on message packages much more easily with `cargo`.
=> Add build.rs to messages to automatically find the message libraries

rclrs/src/context.rs
Currently, when you run e.g. `ros2 run rclrs_examples minimal_publisher --ros-args -r __node:=my/node`, which is an invalid node name, you'll get a message
```
>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:
'Couldn't parse remap rule: '-r __node:=my/node'. Error: Expected lexeme type 1, got 19 at index 10, at /tmp/binarydeb/ros-galactic-rcl-3.1.2/src/rcl/lexer_lookahead.c:238, at /tmp/binarydeb/ros-galactic-rcl-3.1.2/src/rcl/arguments.c:371'
with this new error message:
'context is zero-initialized, at /tmp/binarydeb/ros-galactic-rcl-3.1.2/src/rcl/init.c:238'
rcutils_reset_error() should be called after error handling to avoid this.
<<<
```
This is fixed by checking that the context is indeed valid before calling `rcl_shutdown()` and …
=> Make context initialization and destruction more robust

rclrs/src/context.rs, rclrs/src/node/mod.rs, rclrs/src/node/publisher.rs
Also add a few trait impls for `Node`, since they are required for the doctest.
=> Improve docs for node creation

rclrs/src/error.rs
This can be tested by making two failing calls to rcl after another, e.g. 
```
Context::new(["--ros-args", "-p", "foo&=3"].map(String::from));
Context::new(["--ros-args", "-p", "foo&=3"].map(String::from));
```
Before this change, an error message would be logged about overwriting the error state.
=> Reset error state when converting to RclReturnCode

rclrs/src/context.rs, rclrs/src/error.rs, rclrs/src/lib.rs, rclrs/src/node/mod.rs, rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs
Storing the error string requires a new struct, which I've named `RclrsError`.
This also makes `Display` impls use a period instead of an exclamation mark.
Closes https://github.com/ros2-rust/ros2_rust/issues/111
=> Get error string from rcl layer

rclrs/src/context.rs, rclrs/src/node/mod.rs, rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs, rosidl_runtime_rs/src/sequence.rs, rosidl_runtime_rs/src/string.rs, rosidl_runtime_rs/src/traits.rs
This is required to make multithreading work. For instance, calling publish() on a separate thread doesn't work without these impls.
This is the first time I've needed to implement these traits, but I read up on them and I think this is correct. I believe `rcl` types don't generally care which thread they're on, and therefore can be `Send`.
=> Make all the things Send, and messages Sync as well

examples/minimal_pub_sub/Cargo.toml, examples/minimal_pub_sub/package.xml, rclrs/Cargo.toml, rclrs/package.xml, rosidl_runtime_rs/Cargo.toml, rosidl_runtime_rs/package.xml
I'm happy to add other people like (@jhdcs) too, I just didn't want to speak for them on the question of whether they want to be listed there.
As far as I understand, the semantics of the `authors` field in Cargo.toml is different from the one in `package.xml` in that it doesn't necessarily only list the original author(s).
=> Add Nikolai and Jacob to authors in Cargo.toml and maintainers in package.xml

rclrs/package.xml
Missing clang causes the following error.
```
--- stderr
/opt/ros/humble/include/rcutils/rcutils/allocator.h:25:10: fatal error: 'stdbool.h' file not found
/opt/ros/humble/include/rcutils/rcutils/allocator.h:25:10: fatal error: 'stdbool.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', build.rs:99:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
related issue #75
=> fix: add clang dependency

README.md
We already do this in CI, users should also not need an optimized cargo-ament-build
=> Install cargo-ament-build with --debug

docs/building.md
This adds a note to building.md about this issue.
=> Troubleshooting libraries of custom messages not being found

rclrs/src/error.rs, rclrs/src/lib.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs
As discussed in chat:
- The flatter error type is easier to match against
- The flat model is less code and less noise in the package docs from the many types.
- The "sub-error types" we had before were not actually useful in most cases (e.g. I can't imagine someone wanting to take some specific action in response to all four `NodeError` variants).
- Other client libraries do not have a hierarchy for these error codes either.
I removed the tests because they didn't seem terribly useful, but we can discuss this.
=> Flatten rcl error type

rclrs/src/context.rs, rclrs/src/error.rs, rclrs/src/node/builder.rs, rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs
This is achieved by making CString errors a part of `RclrsError`. This was made possible by #183, which made the error struct an enum. 
Example error output:
```
Error: Could not convert string 'minimal_subscriber' to CString
Caused by:
nul byte found in provided data at position: 13
```
The nul byte is not rendered in the output, as you can see.
=> Make rclrs panic-free as far as possible

rosidl_generator_rs/bin/rosidl_generator_rs, rosidl_generator_rs/cmake/custom_command.cmake, rosidl_generator_rs/cmake/rosidl_generator_rs_generate_interfaces.cmake, rosidl_generator_rs/resource/Cargo.toml.em, rosidl_generator_rs/rosidl_generator_rs/__init__.py
=> feat: obtain interface version from cmake variable

rclrs/src/context.rs, rclrs/src/lib.rs, rclrs/src/node.rs, rclrs/src/node/builder.rs, rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs
I find it confusing and not very descriptive that "handle" is used to refer to both any rcl binding struct, and the `PublisherHandle` etc. types.
This PR changes the variable names of rcl binding types to be more descriptive, e.g. use `rcl_node` as the variable name for an `rcl_node_t`. Afterwards, "handle" refers exclusively to the `PublisherHandle` etc. types.
What's maybe worth discussing: Is `rcl_node` also fine for a `&mut rcl_node_t`?
=> Rename variables of rcl types

rclrs/src/node/publisher.rs
This is a follow-up to https://github.com/ros2-rust/ros2_rust/pull/193#issuecomment-1148745743.
Removing the subscription handle is not as straightforward, since it is used in the `SubscriptionBase` trait. I'll do that in a separate PR.
=> Remove PublisherHandle

rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs
A new variable was added to the struct to store the topic name in a boxed string.
=> Add functions to get topic name to publisher and subscriber

rclrs/Cargo.toml, rclrs/build.rs, rclrs/src/lib.rs, rclrs/src/node.rs, rclrs/src/node/builder.rs, rclrs/src/parameter.rs, rclrs/src/parameter/override_map.rs, rclrs/src/parameter/value.rs, rclrs/src/rcl_wrapper.h
The parameters are not accessible by users yet – I'll do that in a separate PR, since I want to keep them easy to review.
=> Implement functions to get parameters from global arguments

rclrs/src/node/publisher.rs
This fixes `main` not building due to #194
=> Fix publisher handle variable name

rclrs/src/node/publisher.rs, rclrs/src/node/subscription.rs
This is to be consistent with the prevalent style, which is not to use "get_" prefixes for getters.
=> Rename get_topic to topic_name

rosidl_runtime_rs/src/string.rs, rosidl_runtime_rs/src/string/serde.rs
Previously, it was assumed by the $string_conversion_func, for instance, that the output of deref() would be an unsigned integer.
=> Fix a portability problem in rosidl_runtime_rs::String

rclrs/src/error.rs, rclrs/src/node/client.rs, rclrs/src/node/service.rs, rclrs/src/node/subscription.rs, rclrs/src/wait.rs, rclrs/src/wait/exclusivity_guard.rs
Closes #207.
The use of atomic bools follows `rclcpp`'s approach.
=> Ensure that a waitable is only added to one wait set at a time

rclrs/src/node.rs, rclrs/src/node/client.rs, rclrs/src/node/service.rs, rclrs/src/node/subscription.rs
This PR restricts the visibility of `fn new` in waitables (`Subscription`, `Client`, `Service`) so that only other code in the crate can access it. This prevents users from instantiating these structures and therefore we ensure that the only way of creating them is via the `Node::create_X` methods so that any internal logic is not bypassed.
=> Declare fn new in waitables as pub(crate)

rclrs/Cargo.toml, rclrs/src/context.rs, rclrs/src/lib.rs, rclrs/src/node.rs, rclrs/src/node/builder.rs, rclrs/src/node/client.rs, rclrs/src/node/publisher.rs, rclrs/src/node/service.rs, rclrs/src/node/subscription.rs, rclrs/src/parameter/value.rs, rclrs/src/wait.rs
=> Replace parking_lot Mutex with std::sync::Mutex

rosidl_generator_rs/resource/msg_idiomatic.rs.em, rosidl_generator_rs/rosidl_generator_rs/__init__.py
Message packages containing unbounded sequences of WStrings, like test_msgs, would not compile because of this.
There is a special path for sequences of Strings/WStrings in the rosidl_generator_rs template in the `into_rmw_message()` function, but it wasn't taken for `WStrings` because of a copy-paste error.
=> Small bugfix for sequences of WStrings

rosidl_runtime_rs/src/traits.rs
Fix for #185. Implements the Message trait for Box<T: Message> to allow for Boxed publishers and subscribers. 
You should now be able to do 
```rust
let publisher =
node.create_publisher::<Box<std_msgs::msg::String>>("topic", rclrs::QOS_PROFILE_DEFAULT)?;
let mut message = Box::new(std_msgs::msg::String::default());
publisher.publish(&message)?;
```
and 
```rust
let _subscription = node.create_subscription::<Box<std_msgs::msg::String>, _>(
"topic",
rclrs::QOS_PROFILE_DEFAULT,
move |msg: Box<std_msgs::msg::String>| {
num_messages += 1;
println!("I heard boxed: '{}'", (*msg).data);
println!("(Got {} messages so far)", num_messages);
},
)?;
```
It's been 3 years since I last properly wrote Rust so I'm not sure my Cow handling is idiomatic. Also not sure if the trait implementation is in an …
=> Implement Message for Box<T: Message> 

README.md, examples/minimal_pub_sub/Cargo.toml, examples/minimal_pub_sub/src/zero_copy_publisher.rs, examples/minimal_pub_sub/src/zero_copy_subscriber.rs, rclrs/src/node/publisher.rs, rclrs/src/node/publisher/loaned_message.rs, rclrs/src/node/subscription.rs, rclrs/src/node/subscription/readonly_loaned_message.rs, rosidl_runtime_rs/src/traits.rs
I tested it with CycloneDDS and it worked.
The only interesting things are
- I stored a reference to the publisher/subscription in the message, so that the loan can be directly returned when the message is dropped (and it is guaranteed that the publisher/subscription still exists)
- I made `publish()` a method on the `LoanedMessage` that takes no argument, since it can only be used with the publisher that was used to create it, and that publisher is stored inside the message. So this design statically guarantees that a loaned message cannot be published to the wrong publisher.
Closes #136
=> Add support for loaned messages

.github/workflows/rust.yml, rclrs/src/error.rs, rclrs/src/node/graph.rs
The reason is that actions-rs became unmaintained (https://www.reddit.com/r/rust/comments/vyx4oj/actionsrs_organization_became_unmaintained/).
Also, dtolnay's rust-toolchain is simpler (at least in terms of code size).
Both are about equally fast (14s vs 12s in the runs I looked at, so 2s slower, but that doesn't matter compared to other steps).
=> Switch from actions-rs to dtolnay/rust-toolchain

.github/workflows/rust.yml, rclrs_tests/Cargo.toml, rclrs_tests/package.xml, rclrs_tests/src/graph_tests.rs, rclrs_tests/src/lib.rs
This package is meant to test behaviors with dependencies that don't
belong in the rclrs crate - namely, msgs
Addresses #237
=> Add `rclrs_test` package for unit/integration tests

ros2_rust_rolling.repos
The build was broken, with an error about a missing `rosidl_core_generators` package that is a dependency of message packages.
In https://github.com/ros2/rosidl_defaults/pull/22, this package was split off from `rosidl_defaults` into a separate repo, which needed to be added.
I also changed the branches from 'master' to 'rolling', since they were renamed in all ROS 2 repos.
=> Add new rosidl_core repository to ros2_rust_rolling.repos

rclrs/src/context.rs, rclrs/src/node.rs, rclrs/src/publisher.rs, rclrs/src/publisher/loaned_message.rs, rclrs/src/subscription/readonly_loaned_message.rs, rclrs/src/wait.rs, rclrs_tests/src/client_service_tests.rs, rclrs_tests/src/lib.rs, rclrs_tests/src/pub_sub_tests.rs
The tutorial did not work anymore because `Publisher` stopped implementing `Send` after https://github.com/ros2-rust/ros2_rust/pull/212.
This makes sure, with tests, that all types that can implement `Send` and `Sync` do so. This will avoid similar breakages in the future.
Please double-check my reasoning in the safety justifications!
=> Test for Send and Sync implementations, and add missing implementations

.github/workflows/rust.yml
This partly addresses https://github.com/ros2-rust/ros2_rust/issues/135 – I think all feature combinations are too extreme. We can do that before we do a release, but not in a regular CI run.
=> Add the --all-features flag to cargo test

.github/workflows/rust.yml, Dockerfile
This is required now due to https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html#turbofish-for-generics-in-functions-with-impl-trait
Specifying an exact version in CI will also help against the build accidentally breaking due to new clippy lints etc.
=> Specify Rust 1.63 in Dockerfile & CI

rclrs/Cargo.toml
This PR should prevent issues like #267 by requiring a minimum version of the Rust toolchain.
=> Require at least Rust 1.63

examples/minimal_pub_sub/src/zero_copy_subscriber.rs, rclrs/src/publisher.rs, rclrs/src/subscription.rs, rclrs/src/subscription/callback.rs, rclrs/src/subscription/readonly_loaned_message.rs, rclrs_tests/src/pub_sub_tests.rs
With this change, loaned messages can now be used as the argument to subscription callbacks, just like regular messages.
This was not a straightforward extension because
1. `ReadOnlyLoanedMessage` has a lifetime. This required a higher-rank trait bound, which in turn required refactoring the `ArgTuple` trait a bit.
2. The `take_loaned_message()` method was restricted to `Subscription<T: RmwMessage>,` i.e. not available for subscriptions on idiomatic messages. This has been fixed and now the method is implemented for `Subscription<T: Message>` like the other `take*` methods – though you still will get an RMW-native loaned message even if `T` is the idiomatic message type, because idiomatic message types can never be loaned.
=> Extend SubscriptionCallback trait to ReadOnlyLoanedMessage

rclrs_example_msgs/msg/VariousTypes.msg, rosidl_generator_rs/resource/msg.rs.em, rosidl_generator_rs/resource/msg_idiomatic.rs.em, rosidl_generator_rs/resource/msg_rmw.rs.em, rosidl_generator_rs/resource/srv.rs.em, rosidl_generator_rs/rosidl_generator_rs/__init__.py
This will produce:
```
impl VariousTypes {
/// binary, hexadecimal and octal constants are also possible
pub const TWO_PLUS_TWO: i8 = 5;
/// Only unbounded strings are possible
pub const PASSWORD: &'static str = "hunter2";
/// As determined by Edward J. Goodwin
pub const PI: f32 = 3.0;
}
```
Implementation notes:
* Comments on constants are not supported in Foxy, hence the `getattr`
* I changed `constant_value_to_rs` to operate on an rosidl type identifier, not a string. That was more straightforward both for the caller and the implementation of the function.
* I theoretically could have mapped strings to a static variable of type `BoundedString`, but having a constant of type `&str` seemed more useful.
=> Add support for constants to message generation

rclrs/CHANGELOG.rst, rclrs/src/lib.rs, rclrs/src/node.rs, rclrs/src/node/builder.rs, rclrs/src/wait.rs, rclrs/src/wait/guard_condition.rs
- Adds the Guard Condition struct encapsulating rcl_guard_condition_t.
- Adds optional callbacks and a trigger method to approximate the rclcpp
implementation.
- Adds an `add_guard_condition` method to WaitSet to add the
GuardCondition to the WaitSet
=> Adds Guard Conditions

rosidl_generator_rs/resource/msg_rmw.rs.em, rosidl_runtime_rs/src/sequence.rs, rosidl_runtime_rs/src/string.rs, rosidl_runtime_rs/src/traits.rs
This is required for dynamic messages.
=> Add TYPE_NAME constant to messages and make error fields public

docs/CONTRIBUTING.md
Motivation: This documents several guidelines that have so far been implicit. I hope they represent a consensus opinion :)
=> Add notes on unsafe comments, client library consistency, and reviewing to contributing.md

rclrs/src/lib.rs, rclrs/src/wait.rs
`rcl_wait()` modifies the entries in `rcl_wait_set.subscriptions` so that some of them will be null pointers, causing a segfault if called a second time.
As a short term-fix, this makes it so that the wait set can only be used once.
The wait set should be made reusable as part of https://github.com/ros2-rust/ros2_rust/issues/278
=> Fix a segfault when re-using wait set

rclrs/src/node/graph.rs, rclrs_tests/src/graph_tests.rs
It's an easy mistake to make – in https://github.com/ros2/rcl/blob/rolling/rcl/include/rcl/graph.h, some functions have a `no_demangle` argument and others have a `no_mangle` argument. The `no_mangle` argument should be `true`, but it was false.
=> Fix a bug in graph query function and add regression test

examples/message_demo/Cargo.toml, examples/message_demo/package.xml, examples/minimal_client_service/Cargo.toml, examples/minimal_client_service/package.xml, examples/minimal_pub_sub/Cargo.toml, examples/minimal_pub_sub/package.xml, rclrs/Cargo.toml, rclrs/package.xml, rclrs_example_msgs/package.xml, rclrs_tests/Cargo.toml, rclrs_tests/package.xml, rosidl_generator_rs/package.xml, rosidl_runtime_rs/Cargo.toml, rosidl_runtime_rs/package.xml
This commit bumps up the patch version number for a bugfix release.
=> Version 0.3.1

rclrs/package.xml, rclrs/src/lib.rs, rclrs/src/parameter/service.rs, rclrs/src/vendor/builtin_interfaces/mod.rs, rclrs/src/vendor/builtin_interfaces/msg.rs, rclrs/src/vendor/mod.rs, rclrs/src/vendor/rcl_interfaces/mod.rs, rclrs/src/vendor/rcl_interfaces/msg.rs, rclrs/src/vendor/rcl_interfaces/srv.rs, rclrs/vendor_interfaces.py
The parameter services require the rcl_interfaces message and service types. I think this option is preferable to publishing rcl_interfaces on crates.io.
The script included in this PR produces the `vendor` module inside `rclrs` by copying the generated code for the `rcl_interfaces` package and its dependency `builtin_interfaces` and adjusting the submodule paths in the code.
If these packages, or the `rosidl_generator_rs` package, get changed, we can update the `vendor` module by running this script.
=> Vendor rcl_interfaces as a private module into rclrs

rclrs/src/client.rs, rclrs/src/node.rs, rclrs/src/publisher.rs, rclrs/src/service.rs, rclrs/src/subscription.rs
The constructors are not public, so we're free to use internal types as arguments.
This signature makes it possible, or at least easier, to write parameter services that are owned by the node: With this change, the Node does not need to be constructed before the parameter services are constructed, which would somewhat contradict the node owning these services.
=> Make constructor methods for pub/sub/etc. take rcl_node_t mutex

rosidl_runtime_rs/src/string.rs
Implemented `Extend<char>`, `Extend<&'a char>`, `FromIterator<char>`, and `FromIterator<&'a char>` for String and WString.
Of note here is that with this change, String and WString now have interior mutability so they are no longer able to implement `Sync` safely.
Original Issue: https://github.com/ros2-rust/ros2_rust/issues/246
=> Extend string types

rosidl_runtime_rs/src/string/serde.rs
This addresses part of https://github.com/ros2-rust/ros2_rust/issues/214.
I recommend watching the excellent https://www.youtube.com/watch?v=BI_bHCGRgMY tutorial. I mostly followed the implementation of the standard library `String` type.
=> Improve efficiency of deserializing strings

rclrs/src/rcl_bindings.rs, rclrs/src/rcl_wrapper.h, rclrs/src/subscription/message_info.rs
This fixes the following build failure on rolling:
```
error[E0308]: mismatched types
--> src/subscription/message_info.rs:120:19
|
120 |             data: rmw_message_info.publisher_gid.data,
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a fixed size of 24 elements, found one with 16 elements
```
=> Fix hardcoded rmw_gid_t length

.github/workflows/rust.yml
This PR uses the Debian packages from the testing repository for rolling so we can catch API incompatibilities earlier. Given that the rolling job is marked as `continue-on-error` and so it won't cause the entire CI fail, in case there are any build errors, PRs can still be merged.
=> Use ros2-testing debs for rolling

Dockerfile, docs/building.md
Make it easy to create a Docker container with a different ROS distribution for development.
=> Allow usage of different ROS distributions in Dockerfile

rclrs/src/rcl_bindings.rs
=> Disable clippy warnings for u128 types

.github/workflows/rust.yml, ros2_rust_iron.repos
PR for #316
- Made a new `.repos` file for Iron
- Added `iron` as a distro in the github actions
Everything went pretty smooth, not sure what else we want to test
=> Add support for Iron Irwini

rclrs/Cargo.toml, rclrs/build.rs, rosidl_runtime_rs/build.rs
- Upgraded libloading to 0.8
- Added instructions to rerun build scripts if dependent files have changed
- Enabled bindgen to invalidate the built crate whenever any transitively included header files from the wrapper change
- Removed some default true options from our bindgen builder
This enables smoother development workflows when doing things like editing our build scripts, or swapping the source'd version of ROS without requiring a new workspace or having to manually go through and removing the `target/` folder for each crate.
=> Developer workflow improvements to build scripts

docs/writing-your-first-rclrs-node.md, examples/message_demo/src/message_demo.rs, examples/minimal_client_service/src/minimal_client.rs, examples/minimal_client_service/src/minimal_client_async.rs, examples/minimal_client_service/src/minimal_service.rs, examples/minimal_pub_sub/src/minimal_subscriber.rs, examples/minimal_pub_sub/src/zero_copy_subscriber.rs, rclrs/src/lib.rs, rclrs/src/node.rs, rclrs/src/node/builder.rs, rclrs_tests/src/graph_tests.rs
This PR makes `create_node` consistent with other `create_X` functions by return an `Arc`. Additionally added fine-grained locks so that `create_X` functions don't need to take a mutable reference to `self`.
Returning an `Arc` is also akin to `rclcpp`'s behavior, which returns a `shared_ptr` from `create_node`.
=> Return Arc from the create_node function to match other create_X functions

examples/minimal_pub_sub/Cargo.toml, examples/minimal_pub_sub/src/minimal_two_nodes.rs, rclrs/src/executor.rs, rclrs/src/lib.rs, rclrs/src/node.rs, rclrs/src/wait.rs
Moving `spin` and `spin_once` to a similar API as `rclcpp`'s and `rclpy`'s Executor API allows us to run more than one node in a single program and makes it easier to test `node` behaviors.
=> Refactor spin and spin_once to mimic rclcpp's Executor API

rosidl_generator_rs/resource/Cargo.toml.em, rosidl_generator_rs/resource/msg.rs.em, rosidl_generator_rs/resource/msg_idiomatic.rs.em, rosidl_generator_rs/resource/msg_rmw.rs.em, rosidl_generator_rs/resource/srv.rs.em, rosidl_generator_rs/rosidl_generator_rs/__init__.py
=> add serde big array support (fixed #327)

rclrs/src/executor.rs
The loop in the spin function has no pause condition, which will cause the cpu to execute the loop at full load all the time during actual processing. I compared with rclcpp, which can have a pause condition to reduce cpu usage, so I added a pause condition to the loop to reduce cpu usage
https://github.com/ros2/rclcpp/blob/77db1ed25b4c26ab722a13c268521b923606c04d/rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp#L97
=> Fixed an issue where cpu usage remained at 100%

rclrs/src/rcl_bindings.rs
In rust >1.71 our good friend https://github.com/ros2-rust/ros2_rust/issues/320 is a warning once again. 
```
--- stderr: rclrs                                                                                                                                                   
warning: `extern` fn uses type `u128`, which is not FFI-safe
--> /home/sam/rust_ws/build/rclrs/debug/build/rclrs-cc216d91fb97e34d/out/rcl_bindings_generated.rs:5008:9
|
5008 | /         unsafe extern "C" fn(
5009 | |             serialization_support: *mut rosidl_dynamic_typesupport_serialization_support_impl_t,
5010 | |             dynamic_data: *mut rosidl_dynamic_typesupport_dynamic_data_impl_t,
5011 | |             id: rosidl_dynamic_typesupport_member_id_t,
5012 | |             value: u128,
5013 | |         ) -> …
```
=> Allowed the `improper_ctypes_definitions` lint on our generated rcl bindings

examples/message_demo/Cargo.toml, examples/message_demo/package.xml, examples/minimal_client_service/Cargo.toml, examples/minimal_client_service/package.xml, examples/minimal_pub_sub/Cargo.toml, examples/minimal_pub_sub/package.xml, rclrs/Cargo.toml, rclrs/package.xml, rclrs/src/time_source.rs, rclrs/src/vendor/mod.rs, rclrs/src/vendor/rosgraph_msgs/mod.rs, rclrs/src/vendor/rosgraph_msgs/msg.rs, rclrs/vendor_interfaces.py, rclrs_example_msgs/package.xml, rclrs_tests/Cargo.toml, rclrs_tests/package.xml, rosidl_generator_rs/package.xml, rosidl_generator_rs/resource/Cargo.toml.em, rosidl_runtime_rs/Cargo.toml, rosidl_runtime_rs/package.xml
=> Vendorize rosgraph msgs

.github/workflows/rust.yml, rclrs/Cargo.toml, rclrs/build.rs, rclrs/src/arguments.rs, rclrs/src/rcl_bindings.rs, rosidl_runtime_rs/Cargo.toml, rosidl_runtime_rs/build.rs
=> Allow rustdoc to run without a ROS distribution

.github/workflows/rust.yml, Dockerfile, rclrs/src/lib.rs, rosidl_runtime_rs/src/string.rs, rosidl_runtime_rs/src/string/serde.rs
This PR just updates all the GitHub actions to their latest stable version.
=> Update GitHub actions

docs/writing-your-first-rclrs-node.md
This PR fixes a compile error in the tutorial that happened because you cannot move the "node" member out of the republisher
=> Add Arc::clone to the Readme tutorial to fix compile error

rclrs/src/dynamic_message.rs, rclrs_tests/src/dynamic_message_tests.rs
As well as conversion from/to concrete message types.
It's clear logically that the alignment has to be 8, since C messages only contain pointers and primitive types of alignment less than or equal to 8 – with the exception of `long double`. Should we require dynamic messages to be aligned to 16 bytes to support `long double`? Even `test_msgs` doesn't use `long double`.
=> Add the DynamicMessage type itself

examples/message_demo/src/message_demo.rs, rclrs_example_msgs/CMakeLists.txt, rclrs_example_msgs/msg/MyMessage.idl, rosidl_generator_rs/rosidl_generator_rs/__init__.py
Added `wchar` support to `rosidl_runtime_rs`. 
From the [ROS 2 IDL - Interface Definition and Language Mapping](https://design.ros2.org/articles/idl_interface_definition.html) spec
> <h4 id="7414424-wide-char-type">7.4.1.4.4.2.4 Wide Char Type</h4>
> 
> 
> 
> IDL type | Value range
> -- | --
> wchar | A 16-bit wide character
> 
This maps nicely to rust's [u16](https://doc.rust-lang.org/std/primitive.u16.html) type.
You can't actually use `wchar` in a .msg file (see [humble docs for supported .msg file types](https://docs.ros.org/en/humble/Concepts/Basic/About-Interfaces.html#field-types)), but its perfectly valid and supported by [rosidl_parser](https://github.com/ros2/rosidl/blob/iron/rosidl_parser/rosidl_parser/definition.py#L43), which means its valid in a .idl file and we should …
=> Add wchar support

rclrs/Cargo.toml, rclrs/src/time.rs
This commit adds a simple conversion function that converts Time to `builtin_interfaces::msg::Time` like the one in `rclpy`.
=> Adding a simple helper function for converting `rclrs::Time` to a ros message

docs/writing-your-first-rclrs-node.md
Add `Arc<>` type to the `publisher` field in `RepublisherNode` to fix the compile error:
=> Add <Arc> to publisher field to fix the compile error

rclrs/src/qos.rs
This PR adds a default implementation for `QoSProfile` as well as a builder pattern based on the `rclcpp` API.
I split it into a first commit that should be fully uncontroversial and a second commit that contains the builder API for `Duration` based items, which should also be OK I believe.
I intentionally left out all the methods in the other APIs that just set a profile to the requested structure, since while in C++ people might have to do something like:
```
const auto reliability = QoSReliabilityPolicy::Reliable;
auto profile = QoSProfile::SystemDefault().reliability(reliability);
```
In Rust the API is (imho) not so necessary since they can just use struct initialization, such as:
```
let reliability = QoSReliabilityPolicy::Reliable;
let profile = QoSProfile {
reliability, …
```
=> Add default implementation and builder pattern for QoS

rclrs/src/node.rs
Cherry-picked from #342, should help towards #369.
CC @maspe36
=> Move rcl structs to end of Node declaration

rosidl_generator_rs/cmake/rosidl_generator_rs_generate_interfaces.cmake
As discussed [here](https://github.com/ros2-rust/ros2_rust/issues/371#issuecomment-2008696967) there was a strange error that made it impossible to use ros2_rust in an underlay workspace. Packages that have no association to Rust were declaring themselves in the `rust_packages` ament index. This was causing downstream colcon workspaces to redirect their `.cargo/config.toml` file towards non-existent directories. When cargo is directed towards non-existent directories, it considers the situation a build error and exits immediately.
After some challenging investigation, I narrowed the problem down to this: Packages that contain **any** message definitions were invoking the `rosidl_generator_rs`'s extension to the ROS IDL generation pipeline. That extension included the line …
=> Declare rust_packages only when installing Rust IDL bindings

docs/building.md
Fixes https://github.com/ros2-rust/ros2_rust/issues/334
=> Remove references to rclrs not being on crates.io

rclrs/Cargo.toml, rclrs/src/client.rs, rclrs/src/context.rs, rclrs/src/executor.rs, rclrs/src/node.rs, rclrs/src/node/builder.rs, rclrs/src/node/graph.rs, rclrs/src/parameter.rs, rclrs/src/parameter/value.rs, rclrs/src/publisher.rs, rclrs/src/publisher/loaned_message.rs, rclrs/src/service.rs, rclrs/src/subscription.rs, rclrs/src/wait.rs, rclrs/src/wait/guard_condition.rs
For some time now we've noticed spurious segmentation faults and other test failures in CI. This PR aims to eliminate those entirely. I'll break down the problems we observed, followed by how they are being solved by this PR.
Our initial suspicion was that the segmentation faults were being caused by flaws in the drop order of various rcl entities (e.g. `rcl_context_t`, `rcl_node_t`, `rcl_publisher_t`, etc). This suspicion had a lot of merit since rcl specifies that all nodes and middleware primitives must be cleaned up (`fini`ed) before the `rcl_context_t` that they came  from gets `fini`ed. However, the way the rcl objects' lifecycles were being managed, if a `Node` struct gets dropped before its associated primitives (`Subscription`, `Publisher`, `Service`, `Client`) are dropped, then …
=> Correct rcl entity lifecycles and fix spurious test failures

rosidl_runtime_rs/src/string.rs
According to https://design.ros2.org/articles/wide_strings.html, the `string` and `wstring` types must use the UTF-8 and UTF-16 encodings (not necessarily enforced), cannot contain null bytes or words (enforced), and, when bounded, are measured in terms of bytes or words.
Moreover, though the rosidl_runtime_c `U16String` type uses `uint_least16_t`, Rust guarantees the existence of a precise `u16` type, so we should use that instead of `ushort`, which isn't guaranteed to be the same as `uint_least16_t` anyways. (Rust doesn't support platforms where `uint_least16_t != uint16_t`.)
=> Unicode handling in String and WString

rclrs/src/parameter/service.rs
Fix function which took a i8 where c_char is correct, which fixes compilation where those two types aren't equivalent (ex: aarch64)
=> Compile on targets where c_char ≠ i8

rosidl_runtime_rs/src/sequence.rs
resolves: #406
In Rust 1.78, a panic occurs when publishing sequence-type messages containing array types, which could be fixed by adding null pointer handling.
=> Fix panic on sequence_init() when size is 0

docs/writing_a_simple_publisher_and_subscriber.md, examples/rust_pubsub/Cargo.toml, examples/rust_pubsub/package.xml, examples/rust_pubsub/src/simple_publisher.rs, examples/rust_pubsub/src/simple_subscriber.rs
I've decided to write my own Tutorial for your Repository. Suggestions are welcome!
fixes #378
=> Add simple talk/listener tutorial, matching the official ROS 2 documentation #378

rclrs/src/node/graph.rs, rclrs/src/parameter/override_map.rs, rclrs/src/parameter/value.rs, rclrs/src/rcl_bindings.rs
Similar to #416, there are numerous places within rclrs that are at risk of runtime panics because `std::slice::from_raw_parts` may panic when it receives null pointer values. In particular I got this panic while running `cargo test` on rclrs:
```
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
0: rust_begin_unwind
at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/std/src/panicking.rs:652:5
1: core::panicking::panic_nounwind_fmt::runtime
at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:110:18
2: core::panicking::panic_nounwind_fmt
at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library/core/src/panicking.rs:120:5
3: …
```
=> Wrap slice::from_raw_parts to be compatible with rcl

rclrs/src/parameter.rs, rclrs/src/parameter/value.rs
Adds error impls to the error types used by rclrs parameters.
See #412.
=> Add std::error::Error impls to Error enums of `parameter` module

ros2_rust_jazzy.repos
To address #424 this PR adds a .repos file for jazzy.
The new repos file is exactly the same as the file for rolling, but the branches have been switched to jazzy. I used this on 24.04 with the jazzy distro sourced and the build and test went fine.
=> Add a .repos file for jazzy

Dockerfile
This PR updates the rust toolchain installation to v1.75 when using the docker workflow.
See https://github.com/ros2-rust/ros2_rust/pull/420 and https://github.com/ros2-rust/ros2_rust/issues/398
Follow the https://github.com/ros2-rust/ros2_rust/blob/main/docs/building.md guidelines from the top down, branching for the docker workflow and when executing https://github.com/ros2-rust/ros2_rust/blob/main/docs/building.md#building-with-colcon do: 
```
colcon build
```
You should be able to build all packages without errors.
=> Installs rust toolchain 1.75 in the docker workflow.

README.md
This PR fixes the GitHub Action label after the corresponding workflows were renamed on [#429.](https://github.com/ros2-rust/ros2_rust/pull/420).
This PR applies the following changes:
- Creates one label per workflow (`rust-minimal.yaml` and `rust-stable.yaml`).
- Removes the status table in favor of a row of labels since only Ubuntu is currently supported (and it easily gets outdated since `ubuntu-latest` is used for CI jobs).
- Adds a new label for the repository license.
Rendered README file visually inspected.
=> Fix GHA status labels

.github/workflows/rust-minimal.yml, .github/workflows/rust-stable.yml
This PR fixes a GitHub Action warning related to using the deprecated set-output command.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
This PR applies the following changes:
- Removes the command in favor of environment files as indicated by the documentation.
CI should pass and warning message shall be gone.
=> Fix GHA set-output command warning

.github/workflows/rust-minimal.yml, .github/workflows/rust-stable.yml, Dockerfile, README.md, docs/building.md
Now that [cargo-ament-build](https://pypi.org/project/cargo-ament-build/) is avaialble via PyPI as a Python wheel and that [cargo-ros-cargo](https://pypi.org/project/colcon-ros-cargo/) depends on it, we can install both in one go.
=> chore: remove references to installing cargo-ament-build via cargo

examples/message_demo/src/message_demo.rs, examples/rclrs_example_msgs/msg/VariousTypes.msg
The example message `VariousTypes` has a `string<=3` with a default value containing three characters which each have a length of two bytes in utf-8. This means the real length of the default value is 6 bytes even though the byte limit is `<=3`.
This PR changes the default value to be `"aou"` to be three bytes long. The other bounded string is a wide string (utf-16), so it can remain as-is.
To observe the problem, use `$ cargo run` in the `message_demo` example to see it return an error code if you use the `main` branch. Then use the branch of this PR and see that it does not return an error code.
=> Fix buffer overflow for bounded sequence example

README.md, docs/writing_a_simple_publisher_and_subscriber.md
* Small change to fix some capitalization on the Rust code pasted in the pub/sub tutorial. 
* Add a link to the installation instruction from the main README.md
=> Minor fixes to pub sub tutorial

rclrs/Cargo.toml, rclrs/build.rs
Alternative to https://github.com/ros2-rust/ros2_rust/pull/451, fixes https://github.com/ros2-rust/ros2_rust/issues/449.
It turns out `bindgen` fully dropped the `which` dependency that caused the issue in the first place in 0.70 in [this PR](https://github.com/rust-lang/rust-bindgen/pull/2809/).
We can just avoid the issue altogether by bumping `bindgen`. Why not 0.71? Because I encountered a build error due to an outdated lock file that would be fixed by [this PR](https://github.com/rust-lang/rust-bindgen/pull/3048) that is however not released. If we were to bump to 0.71 users that have a semi-old lockfile will have a failing build.
My proposal would be, once that PR is released, to update to the version with it (most likely a 0.71.2).
The one line code diff addresses a deprecated API. …
=> Bumb bindgen dependency to 0.70

docs/building.md
CI failing due to https://github.com/ros2-rust/ros2_rust/issues/449
=> Fix docker build instructions missing build context

Dockerfile
- Change the pip command based on the ROS_DISTRO argument
- Swap to the PyPi version of [colcon-ros-cargo](https://pypi.org/project/colcon-ros-cargo/)
- Only install `colcon-ros-cargo` as it lists `colcon-cargo` and `cargo-ament-build` as dependencies ([link](https://github.com/colcon/colcon-ros-cargo/blob/main/setup.cfg#L29))
=> Add support for the newer Rolling and Jazzy distros in our dev Dockerfile

rclrs/src/publisher.rs
This should close #456 
This is my first contribution to ros2_rust and I am not sure about the return code handling and safety comment.
Any feedback is welcomed.
=> Add Publisher::get_subscription_count

docs/CONTRIBUTING.md
In `CONTRIBUTING.md`, the link to Matrix chat `+rosorg-rust` is no longer valid, this PR changes it to `!AiYXdTWExqamTdatBl` (obtained from #286)
=> Corrects link to Matrix chat

rclrs/src/client.rs, rclrs/src/node.rs, rclrs/src/parameter.rs, rclrs/src/parameter/service.rs, rclrs/src/service.rs, rclrs/src/subscription.rs
This is aimed at fixing #462. With these changes, users will no longer need to explicitly hold onto the `Arc<Node>` in order to keep their subscriptions, services, or clients running.
This will be implemented differently as we move through the async execution PRs, but this PR will be a quick and effective stop gap in the meantime.
=> Fix RAII for subscription, client, and service

examples/message_demo/Cargo.toml, examples/minimal_client_service/Cargo.toml, examples/minimal_pub_sub/Cargo.toml
A recent version bump in `backtrace` is no longer compatible with Rust version 1.75, despite being a patch increase.
This PR forces a fixed version for several examples that have a transitive dependency on `backtrace` to keep it compatible with Rust 1.75. This should fix CI failures that recently started happening.
=> Force backtrace version that is compatible with 1.75

.github/workflows/rust-win.yml
This PR adds a GitHub action which:
* Installs ROS2 windows binary with new pixi installation
* Builds the current ros2_rust with added modules with visual studio 2022 (with action msvc-dev-cmd)
* Runs minimal examples and cargo test
This is for windows-server 2022 (currently latest) and ROS2 rolling nightly binaries
I would wait a bit more before adding instructions for the windows install as there are more changing upcoming for the installation instructions, but luckily it wasn't much. I tried to add those extra steps in 'Get prebuild ROS files and unzip' and 'Build the rust package'. Also currently, the binaries of windows ROS2 install are hardcoded that they need to be installed in C:\pixi_ws but that will soon change as well (see this …
=> Adding windows github action

.github/workflows/rust-minimal.yml, .github/workflows/rust-stable.yml, rclrs/Cargo.toml, rclrs/build.rs, rclrs/src/rcl_bindings.rs
This PR is the `rclrs` counterpart of https://github.com/ros2-rust/rosidl_runtime_rs/pull/14, given that we'll use this feature for publishing the crate onto crates.io in addition to docs.rs, `use_ros_shim` might make more sense.
=> build: rename generate_docs feature to use_ros_shim

rclrs/src/executor.rs, rclrs/src/executor/basic_executor.rs, rclrs/src/node.rs, rclrs/src/publisher.rs, rclrs/src/subscription.rs
This PR fixes a subtle bug that could cause subscriptions, clients, and services to stall out where new messages fail to wake up the wait set because the subscription, client, or service itself has not been added to the wait set yet.
The fix itself is very simple:
```rust
pub(crate) fn add_to_wait_set(&self, waitable: Waitable) {
self.channel.add_to_wait_set(waitable);
let _ = self.wakeup_wait_set.trigger(); // <--- We were forgetting to do this
}
```
This was an oversight that was missed in the original PR that introduced async execution. The result was:
* We send off an instruction to add a new waitable to the wait set
* The wait set is never told to wake up, so it keeps waiting on its current set of primitives
* Since the wait set doesn't wake up, the new waitable never gets added to …
=> Wake up wait set when adding a new waitable

rclrs/Cargo.toml, rclrs/src/client.rs, rclrs/src/lib.rs, rclrs/src/node.rs, rclrs/src/publisher.rs, rclrs/src/publisher/loaned_message.rs, rclrs/src/service.rs, rclrs/src/subscription.rs, rclrs/src/subscription/into_async_subscription_callback.rs, rclrs/src/subscription/into_node_subscription_callback.rs, rclrs/src/subscription/readonly_loaned_message.rs, rclrs/src/vendor/example_interfaces/action.rs, rclrs/src/vendor/example_interfaces/mod.rs, rclrs/src/vendor/example_interfaces/msg.rs, rclrs/src/vendor/example_interfaces/srv.rs, rclrs/src/vendor/mod.rs, rclrs/src/vendor/rcl_interfaces/msg.rs, rclrs/src/vendor/rcl_interfaces/srv.rs, rclrs/src/vendor/test_msgs/action.rs, rclrs/src/vendor/test_msgs/mod.rs, rclrs/src/vendor/test_msgs/msg.rs, rclrs/src/vendor/test_msgs/srv.rs, rclrs/src/worker.rs, rclrs/vendor_interfaces.py
This PR vendorizes the `example_interfaces` and `test_msgs` packages so that `cargo update` can work during the release-plz job (see https://github.com/ros2-rust/ros2_rust/actions/runs/16942715079/job/48016392561)
=> feat: vendorize messages so that cargo update works

.github/workflows/release-plz.yml, rclrs/Cargo.toml, rclrs/build.rs, rclrs/src/rcl_bindings.rs
This PR lets the user set the target ROS distro via `RUSTFLAGS = --cfg ros_distro="<ros_distro>"`
This also fixes an issue in the release-plz job that prevented it from building the crate before being published to crates.io
=> fix: let user pass compiler flag to specify the ROS distro
